server:
  port: 8761                          #指定Eureka实例的端口
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false
#参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_node
#参考文档：http://my.oschina.net/buwei/blog/618756
