server:
  port: 8002
spring:
  application:
    name: microservice-provider-user     #用于指定注册到Eureka Service上的应用名称
  jpa:
    database: h2
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           #指定数据源
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: ld
    password: 123456
    platform: h2                         #指定数据源类型
    schema:classpath: schema.sql         #指定h2数据库的建表脚本
    data:classpath: data.sql             #指定h2数据库的数据脚本
  h2:
    console:
      path: /h2-console
      enabled: true
logging:                                #配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    #registerWithEureka: false
    #fetchRegistry: false
    instance:
      prefer-ip-address: true            #表示将自己的IP注册到Eureka Server，如不配置该属性或将其设置为false，
